using System;

namespace Framework.Netcode;

/// <summary>
/// Shared packet functionality for client-to-server and server-to-client packets.
/// </summary>
public abstract class GamePacket
{
    public const int MaxSize = 8192;

    private byte[] _data;
    private long _size;

    /// <summary>
    /// Serializes opcode and payload into a byte buffer.
    /// </summary>
    public void Write()
    {
        using PacketWriter writer = new();
        writer.Write(GetOpcode());
        Write(writer);

        _data = writer.Stream.ToArray();
        _size = writer.Stream.Length;
    }

    /// <summary>
    /// Returns the serialized byte buffer. Must call <see cref="Write"/> first.
    /// </summary>
    public byte[] GetData()
    {
        if (_data == null)
        {
            throw new InvalidOperationException(
                $"{GetType().Name}: Write() must be called before GetData().");
        }

        return _data;
    }

    /// <summary>
    /// Gets the size of the most recently serialized packet payload.
    /// </summary>
    public long GetSize()
    {
        return _size;
    }

    /// <summary>
    /// Returns the opcode associated with this packet type.
    /// </summary>
    public abstract ushort GetOpcode();

    /// <summary>
    /// Writes payload data. Generated by PacketGen in partial classes.
    /// </summary>
    public virtual void Write(PacketWriter writer)
    {
    }

    /// <summary>
    /// Reads payload data. Generated by PacketGen in partial classes.
    /// </summary>
    public virtual void Read(PacketReader reader)
    {
    }
}
