using System;

namespace __TEMPLATE__.Netcode;

/// <summary>
/// Shared packet functionality for client-to-server and server-to-client packets.
/// </summary>
public abstract class GamePacket
{
    /// <summary>
    /// Maximum serialized packet size supported by the netcode layer.
    /// </summary>
    public const int MaxSize = 8192;

    private byte[] _data = null!;
    private long _size;

    /// <summary>
    /// Serializes opcode and payload into a byte buffer.
    /// </summary>
    public void Write()
    {
        using PacketWriter writer = new();
        WriteOpcode(writer);
        Write(writer);

        _data = writer.Stream.ToArray();
        _size = writer.Stream.Length;
    }

    /// <summary>
    /// Returns the serialized byte buffer. Must call <see cref="Write"/> first.
    /// </summary>
    /// <returns>Serialized packet bytes.</returns>
    public byte[] GetData()
    {
        // Throw when packet data has not been serialized yet.
        if (_data == null)
        {
            throw new InvalidOperationException(
                $"{GetType().Name}: Write() must be called before GetData().");
        }

        return _data;
    }

    /// <summary>
    /// Gets the size in bytes of the most recently serialized packet.
    /// </summary>
    /// <returns>Serialized packet size in bytes.</returns>
    public long GetSize()
    {
        return _size;
    }

    /// <summary>
    /// Returns the opcode associated with this packet type, widened to ushort.
    /// </summary>
    /// <returns>Opcode associated with this packet type.</returns>
    public abstract ushort GetOpcode();

    /// <summary>
    /// Writes the opcode bytes using the wire width configured via <see cref="PacketRegistryAttribute"/>.
    /// </summary>
    /// <param name="writer">Packet writer receiving opcode bytes.</param>
    protected abstract void WriteOpcode(PacketWriter writer);

    /// <summary>
    /// Writes payload data. Generated by PacketGen in partial classes.
    /// </summary>
    /// <param name="writer">Packet writer receiving payload fields.</param>
    public virtual void Write(PacketWriter writer)
    {
    }

    /// <summary>
    /// Reads payload data. Generated by PacketGen in partial classes.
    /// </summary>
    /// <param name="reader">Packet reader that provides payload fields.</param>
    public virtual void Read(PacketReader reader)
    {
    }
}
