using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;

namespace Template.OptionsGen;

internal sealed class OptionsSettingsSourceBuilder : IOptionsSettingsSourceBuilder
{
    public string BuildSource(INamedTypeSymbol optionsSettings, IReadOnlyList<OptionSettingSpec> specs)
    {
        string namespaceName = optionsSettings.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : optionsSettings.ContainingNamespace.ToDisplayString();

        Dictionary<string, string> propertyNamesBySaveKey = BuildUniquePropertyNames(specs);
        StringBuilder builder = new();

        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        if (!string.IsNullOrWhiteSpace(namespaceName))
        {
            builder.Append("namespace ").Append(namespaceName).AppendLine(";");
            builder.AppendLine();
        }

        builder.Append("public sealed partial class ")
            .Append(OptionsGenConstants.OptionsSettingsTypeName)
            .AppendLine();
        builder.AppendLine("{");

        foreach (OptionSettingSpec spec in specs)
        {
            string propertyName = propertyNamesBySaveKey[spec.SaveKey];
            string saveKeyLiteral = SymbolDisplay.FormatLiteral(spec.SaveKey, quote: true);

            builder.Append("    public ")
                .Append(OptionValueKindNaming.GetTypeKeyword(spec.ValueKind))
                .Append(" ")
                .Append(propertyName)
                .AppendLine();
            builder.AppendLine("    {");
            builder.Append("        get => ")
                .Append(OptionValueKindNaming.GetGetterName(spec.ValueKind))
                .Append("(")
                .Append(saveKeyLiteral)
                .Append(", ")
                .Append(spec.DefaultLiteral)
                .AppendLine(");");
            builder.Append("        set => ")
                .Append(OptionValueKindNaming.GetSetterName(spec.ValueKind))
                .Append("(")
                .Append(saveKeyLiteral)
                .AppendLine(", value);");
            builder.AppendLine("    }");
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static Dictionary<string, string> BuildUniquePropertyNames(IReadOnlyList<OptionSettingSpec> specs)
    {
        Dictionary<string, string> namesBySaveKey = new(StringComparer.Ordinal);
        HashSet<string> usedNames = new(StringComparer.Ordinal);

        foreach (OptionSettingSpec spec in specs)
        {
            string baseName = ToIdentifier(spec.SaveKey);
            string name = baseName;
            int suffix = 2;

            while (!usedNames.Add(name))
            {
                name = baseName + suffix.ToString(CultureInfo.InvariantCulture);
                suffix++;
            }

            namesBySaveKey[spec.SaveKey] = name;
        }

        return namesBySaveKey;
    }

    private static string ToIdentifier(string saveKey)
    {
        StringBuilder builder = new();
        bool uppercaseNext = true;

        foreach (char character in saveKey)
        {
            if (!char.IsLetterOrDigit(character))
            {
                uppercaseNext = true;
                continue;
            }

            if (builder.Length == 0)
            {
                builder.Append(char.ToUpperInvariant(character));
                uppercaseNext = false;
                continue;
            }

            builder.Append(uppercaseNext ? char.ToUpperInvariant(character) : character);
            uppercaseNext = false;
        }

        string identifier = builder.Length == 0 ? "Setting" : builder.ToString();

        if (char.IsDigit(identifier[0]))
            identifier = "Setting" + identifier;

        if (SyntaxFacts.GetKeywordKind(identifier) != SyntaxKind.None)
            identifier = "@" + identifier;

        return identifier;
    }
}
